%% Regression checks for plotspec dynamic metric masks

fprintf('[%s] harmonic-lobe NFMethod and in-band THD checks\n', mfilename);

%% NFMethod='exclude' must remove windowed harmonic lobes from SNR.
N = 8192;
n = 0:N-1;
fundBin = 257;
hd2_dbc = -60;
noise_dbc = -80;
noiseBin = 1400;

sig = sin(2*pi*fundBin*n/N) ...
    + 10^(hd2_dbc/20) * sin(2*pi*2*fundBin*n/N) ...
    + 10^(noise_dbc/20) * sin(2*pi*noiseBin*n/N);

[~, sndr, ~, snr, thd] = plotspec( ...
    sig, 1, 2, 5, ...
    'window', 'hann', ...
    'sideBin', 1, ...
    'NFMethod', 'exclude', ...
    'assumedSignal', 0, ...
    'disp', false, ...
    'label', false);

expected_sndr = 10*log10(1 / (10^(hd2_dbc/10) + 10^(noise_dbc/10)));

assert(abs(snr - 80) < 1e-9, 'NFMethod=exclude should remove HD2 lobe from SNR noise.');
assert(abs(thd - hd2_dbc) < 1e-9, 'THD should integrate the HD2 lobe.');
assert(abs(sndr - expected_sndr) < 1e-9, 'SNDR should still include both HD2 and noise.');

%% OSR analysis band should exclude out-of-band harmonics from THD.
fundBin = 900;
hd2_dbc = -60;
sig = sin(2*pi*fundBin*n/N) ...
    + 10^(hd2_dbc/20) * sin(2*pi*2*fundBin*n/N);

[~, ~, ~, ~, thd_full_band] = plotspec( ...
    sig, 1, 2, 5, ...
    'window', 'rect', ...
    'sideBin', 0, ...
    'NFMethod', 'exclude', ...
    'OSR', 1, ...
    'assumedSignal', 0, ...
    'disp', false, ...
    'label', false);

[~, sndr_osr4, ~, ~, thd_osr4] = plotspec( ...
    sig, 1, 2, 5, ...
    'window', 'rect', ...
    'sideBin', 0, ...
    'NFMethod', 'exclude', ...
    'OSR', 4, ...
    'assumedSignal', 0, ...
    'disp', false, ...
    'label', false);

assert(abs(thd_full_band - hd2_dbc) < 1e-9, 'Full-band THD should include HD2.');
assert(thd_osr4 < -140 || isinf(thd_osr4), 'OSR=4 THD should ignore out-of-band HD2.');
assert(sndr_osr4 > 140, 'OSR=4 SNDR should also ignore out-of-band HD2.');

%% Harmonic lobes near the fundamental should keep the visible annulus.
N = 1024;
n = 0:N-1;
fundBin = 340;
hd2_dbc = -60;
noise_dbc = -80;
noiseBin = 100;

sig = sin(2*pi*fundBin*n/N) ...
    + 10^(hd2_dbc/20) * sin(2*pi*2*fundBin*n/N) ...
    + 10^(noise_dbc/20) * sin(2*pi*noiseBin*n/N);

[~, sndr_near, ~, snr_near, thd_near] = plotspec( ...
    sig, 1, 2, 2, ...
    'window', 'rect', ...
    'sideBin', 2, ...
    'NFMethod', 'exclude', ...
    'assumedSignal', 0, ...
    'disp', false, ...
    'label', false);

expected_sndr_near = 10*log10(1 / (10^(hd2_dbc/10) + 10^(noise_dbc/10)));

assert(abs(snr_near - 80) < 1e-9, 'Near-fundamental HD2 annulus should be excluded from SNR noise.');
assert(abs(thd_near - hd2_dbc) < 1e-9, 'Near-fundamental HD2 annulus should remain in THD.');
assert(abs(sndr_near - expected_sndr_near) < 1e-9, 'SNDR should include near-fundamental HD2 and noise.');
